import { createServerFn } from "@tanstack/react-start";
import type { BoundingBox, CategoryKey, Establishment } from "./types";
import { buildAroundQuery } from "./overpass-query";
import { fetchWithTimeout, OSM_UA, OVERPASS_MIRRORS } from "./geo.server";
import { externalVerificationConfigured, verifyLeads, type LeadVerification } from "./web-verification";

export interface OverpassElement { type:string; id:number; lat?:number; lon?:number; center?:{lat:number;lon:number}; tags?:Record<string,string>; }
export interface PlaceSuggestion { label:string; shortLabel:string; lat:number; lon:number; boundingBox:BoundingBox|null; }
type NominatimAddress={city?:string;town?:string;municipality?:string;village?:string;state?:string;country?:string;country_code?:string};
type NominatimResult={display_name:string;name?:string;lat:string;lon:string;type?:string;class?:string;address?:NominatimAddress;boundingbox?:[string,string,string,string]};

function normalizeText(v:string|null|undefined){return(v??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim();}
function cityName(r:NominatimResult){return normalizeText(r.address?.city??r.address?.town??r.address?.municipality??r.address?.village??"");}
function resultTypePriority(r:NominatimResult){const type=normalizeText(r.type),cls=normalizeText(r.class);if(cls==="place"&&["city","town","municipality"].includes(type))return 500;if(cls==="boundary"&&type==="administrative")return 420;if(type==="village")return 280;if(type==="suburb"||type==="neighbourhood")return 120;return 20;}
function matchScore(q:string,r:NominatimResult){const nq=normalizeText(q),name=normalizeText(r.name),city=cityName(r),display=normalizeText(r.display_name);let s=resultTypePriority(r);if(name===nq)s+=500;else if(name.startsWith(nq))s+=300;else if(name.includes(nq))s+=120;if(city===nq)s+=500;else if(city.startsWith(nq))s+=260;else if(city.includes(nq))s+=120;if(display.startsWith(`${nq},`))s+=180;return s;}
function rankPlaceResults(q:string,rs:NominatimResult[]){const nq=normalizeText(q),seen=new Set<string>();return rs.filter(r=>!r.address?.country_code||r.address.country_code.toLowerCase()==="br").filter(r=>{const k=`${Number(r.lat).toFixed(5)}:${Number(r.lon).toFixed(5)}`;if(seen.has(k))return false;seen.add(k);return true;}).map((item,index)=>({item,score:matchScore(nq,item),index})).sort((a,b)=>b.score-a.score||a.index-b.index).filter(x=>x.score>=140).slice(0,8).map(x=>x.item);}
async function queryPlaces(q:string, featuretype?:"city"):Promise<NominatimResult[]>{const u=new URL("https://nominatim.openstreetmap.org/search");[["format","jsonv2"],["limit","20"],["q",q],["countrycodes","br"],["accept-language","pt-BR"],["addressdetails","1"],["namedetails","1"],["dedupe","1"],...(featuretype?[["featuretype",featuretype]]:[])].forEach(([k,v])=>u.searchParams.set(k,v));try{const r=await fetchWithTimeout(u.toString(),{headers:{Accept:"application/json","User-Agent":OSM_UA}},8000);if(!r.ok)return[];return await r.json() as NominatimResult[];}catch{return[];}}
async function queryOverpassMirror(m:string,q:string):Promise<OverpassElement[]|null>{try{const r=await fetchWithTimeout(m,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded","User-Agent":OSM_UA},body:`data=${encodeURIComponent(q)}`},14000);if(!r.ok)return null;const j=await r.json() as{elements?:OverpassElement[]};return j.elements??[];}catch{return null;}}
function merge(responses:Array<OverpassElement[]|null>){const m=new Map<string,OverpassElement>();for(const rs of responses)for(const e of rs??[]){const k=`${e.type}-${e.id}`;if(!m.has(k))m.set(k,e);}return[...m.values()];}
async function queryOverpass(q:string){const rs=await Promise.all(OVERPASS_MIRRORS.map(m=>queryOverpassMirror(m,q)));if(!rs.some(Boolean))return null;return merge(rs);}
function haversineKm(aLat:number,aLon:number,bLat:number,bLon:number){const R=6371;const dLat=(bLat-aLat)*Math.PI/180;const dLon=(bLon-aLon)*Math.PI/180;const s=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function toPlaceSuggestion(r:NominatimResult):PlaceSuggestion{const parts=r.display_name.split(",").map(p=>p.trim()),city=r.address?.city??r.address?.town??r.address?.municipality??r.address?.village??r.name??parts[0],state=r.address?.state,lat=Number(r.lat),lon=Number(r.lon);return{label:r.display_name,shortLabel:[city,state].filter(Boolean).join(", ")||parts.slice(0,3).join(", "),lat,lon,boundingBox:{south:lat-.06,north:lat+.06,west:lon-.07,east:lon+.07}};}

export const searchPlacesServer=createServerFn({method:"POST"}).validator((data:{q:string})=>data).handler(async({data}):Promise<PlaceSuggestion[]>=>{const q=data.q.trim().replace(/\s+/g," ");if(q.length<2)return[];const exact=await queryPlaces(`${q}, Brasil`,"city");const broad=await queryPlaces(q);const ranked=rankPlaceResults(q,[...exact,...broad]);return ranked.map(toPlaceSuggestion);});

export const searchOverpassServer=createServerFn({method:"POST"}).validator((data:{area:BoundingBox;categories:CategoryKey[]})=>data).handler(async({data})=>{const lat=(data.area.south+data.area.north)/2,lon=(data.area.west+data.area.east)/2;const radiusMeters=7000;const primary=await queryOverpass(buildAroundQuery(lat,lon,data.categories,radiusMeters));if(primary===null)throw new Error("A fonte de estabelecimentos está indisponível no momento. Tente novamente em alguns segundos.");const nearby=primary.filter(e=>{const p=e.center??(e.lat!==undefined&&e.lon!==undefined?{lat:e.lat,lon:e.lon}:null);return p?haversineKm(lat,lon,p.lat,p.lon)<=7:false;});return{elements:nearby};});

export const verifyLeadsServer=createServerFn({method:"POST"}).validator((data:{leads:Establishment[]})=>data).handler(async({data}):Promise<{leads:(Establishment&{verification:LeadVerification})[];external:boolean}>=>{if(!externalVerificationConfigured())return{leads:data.leads.map(lead=>({...lead,verification:{status:"unverified",score:0,reasons:["Verificação externa não configurada; usados os dados do OpenStreetMap."],checked:false,foundDigitalPresence:false,foundWebsite:false,contactConfidence:"low" as const}})),external:false};return{leads:await verifyLeads(data.leads),external:true};});
