import { createServerFn } from "@tanstack/react-start";
import type { BoundingBox, CategoryKey, Establishment } from "./types";
import { buildOverpassQuery } from "./overpass-query";
import { fetchWithTimeout, OSM_UA, OVERPASS_MIRRORS } from "./geo.server";
import { externalVerificationConfigured, verifyLeads, type LeadVerification } from "./web-verification";

export interface OverpassElement { type: string; id: number; lat?: number; lon?: number; center?: { lat: number; lon: number }; tags?: Record<string, string>; }
export interface PlaceSuggestion { label: string; shortLabel: string; lat: number; lon: number; boundingBox: BoundingBox | null; }
type NominatimAddress = { city?: string; town?: string; municipality?: string; village?: string; state?: string; country?: string; country_code?: string };
type NominatimResult = { display_name: string; name?: string; lat: string; lon: string; type?: string; class?: string; address?: NominatimAddress; boundingbox?: [string, string, string, string] };
type PhotonFeature = { type?: string; properties?: { name?: string; city?: string; state?: string; country?: string; countrycode?: string; type?: string; osm_value?: string; osm_key?: string; }; geometry?: { type?: string; coordinates?: [number, number] }; };
type PhotonResponse = { features?: PhotonFeature[] };

function normalizeText(v: string | null | undefined) { return (v ?? "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim(); }
function editDistance(a: string, b: string): number { const left = normalizeText(a), right = normalizeText(b); if (left === right) return 0; if (!left.length) return right.length; if (!right.length) return left.length; const prev = new Array<number>(right.length + 1), curr = new Array<number>(right.length + 1); for (let j = 0; j <= right.length; j++) prev[j] = j; for (let i = 1; i <= left.length; i++) { curr[0] = i; for (let j = 1; j <= right.length; j++) { const leftChar = left[i - 1] ?? ""; const rightChar = right[j - 1] ?? ""; const cost = leftChar === rightChar ? 0 : 1; curr[j] = Math.min(curr[j - 1] ?? Number.POSITIVE_INFINITY, prev[j] ?? Number.POSITIVE_INFINITY, (prev[j - 1] ?? Number.POSITIVE_INFINITY) + cost); } for (let j = 0; j <= right.length; j++) prev[j] = curr[j] ?? j; } return prev[right.length] ?? Math.max(left.length, right.length); }
function toPlaceSuggestion(r: NominatimResult): PlaceSuggestion { const parts = r.display_name.split(",").map((p) => p.trim()); const city = r.address?.city ?? r.address?.town ?? r.address?.municipality ?? r.address?.village ?? r.name ?? parts[0] ?? ""; const state = r.address?.state; const lat = Number(r.lat); const lon = Number(r.lon); const rawBox = r.boundingbox; const boundingBox = rawBox && rawBox.length === 4 ? { south: Number(rawBox[0]), north: Number(rawBox[1]), west: Number(rawBox[2]), east: Number(rawBox[3]) } : { south: lat - 0.025, north: lat + 0.025, west: lon - 0.03, east: lon + 0.03 }; return { label: r.display_name, shortLabel: [city, state].filter(Boolean).join(", ") || parts.slice(0, 3).join(", "), lat, lon, boundingBox }; }
function placeName(r: NominatimResult) { return normalizeText(r.address?.city ?? r.address?.town ?? r.address?.municipality ?? r.address?.village ?? r.name ?? ""); }
function resultTypePriority(r: NominatimResult) { const type = normalizeText(r.type), cls = normalizeText(r.class); if (cls === "place" && ["city", "town", "municipality", "village"].includes(type)) return 300; if (cls === "boundary" && type === "administrative") return 260; if (type === "city" || type === "town") return 220; if (type === "suburb" || type === "neighbourhood") return 100; return 20; }
function isCityLike(r: NominatimResult) { const type = normalizeText(r.type), cls = normalizeText(r.class); return (cls === "place" && ["city", "town", "municipality", "village"].includes(type)) || (cls === "boundary" && type === "administrative") || ["city", "town"].includes(type); }
function matchScore(q: string, r: NominatimResult) { const name = normalizeText(r.name), city = placeName(r), display = normalizeText(r.display_name); let s = resultTypePriority(r); if (name === q) s += 500; else if (name.startsWith(q)) s += 300; else if (name.includes(q)) s += 120; if (city === q) s += 450; else if (city.startsWith(q)) s += 320; else if (city.includes(q)) s += 140; if (display.startsWith(`${q},`)) s += 150; const ts = q.split(" ").filter(Boolean); if (ts.length) s += Math.round(ts.filter((t) => [name, city, display].some((h) => h.split(" ").some((x) => x === t))).length / ts.length * 100); return s; }
function fuzzyDistance(q: string, r: NominatimResult) { const name = normalizeText(r.name), city = placeName(r); const candidates = [name, city].filter(Boolean); return candidates.length ? Math.min(...candidates.map((value) => editDistance(q, value))) : Number.POSITIVE_INFINITY; }
function fuzzyLimit(q: string) { const length = normalizeText(q).replace(/\s+/g, "").length; return length <= 5 ? 1 : length <= 8 ? 2 : 2; }
function dedupeResults(rs: NominatimResult[]) { const seen = new Set<string>(); return rs.filter((r) => !r.address?.country_code || r.address.country_code.toLowerCase() === "br").filter((r) => { const k = `${Number(r.lat).toFixed(5)}:${Number(r.lon).toFixed(5)}`; if (seen.has(k)) return false; seen.add(k); return true; }); }
function rankPlaceResults(q: string, rs: NominatimResult[]) { const qn = normalizeText(q); return dedupeResults(rs).map((item, index) => ({ item, score: matchScore(qn, item), index })).sort((a, b) => b.score - a.score || a.index - b.index).filter((x) => x.score >= 100).slice(0, 8).map((x) => x.item); }
function rankFuzzyPlaceResults(q: string, rs: NominatimResult[]) { const qn = normalizeText(q), limit = fuzzyLimit(qn); return dedupeResults(rs).map((item, index) => ({ item, distance: fuzzyDistance(qn, item), cityLike: isCityLike(item), score: matchScore(qn, item), index })).filter((x) => x.distance <= limit).sort((a, b) => Number(b.cityLike) - Number(a.cityLike) || a.distance - b.distance || b.score - a.score || a.index - b.index).slice(0, 8).map((x) => x.item); }
async function queryPlaces(q: string, extra: Partial<Record<string, string>> = {}): Promise<NominatimResult[]> { const u = new URL("https://nominatim.openstreetmap.org/search"); const params: Array<[string, string]> = [["format", "jsonv2"], ["limit", "50"], ["q", q], ["countrycodes", "br"], ["accept-language", "pt-BR"], ["addressdetails", "1"], ["namedetails", "1"], ["dedupe", "1"]]; for (const [k, v] of Object.entries(extra)) if (v !== undefined) params.push([k, v]); for (const [k, v] of params) u.searchParams.set(k, v); try { const r = await fetchWithTimeout(u.toString(), { headers: { Accept: "application/json", "User-Agent": OSM_UA } }, 8000); if (!r.ok) return []; return await r.json() as NominatimResult[]; } catch { return []; } }
function photonToNominatimResult(f: PhotonFeature): NominatimResult | null { const p = f.properties; const c = f.geometry?.coordinates; if (!p || !c || c.length < 2 || (p.countrycode && p.countrycode.toLowerCase() !== "br")) return null; const name = p.name ?? p.city; if (!name) return null; const city = p.city ?? name; const state = p.state; return { display_name: [name, city !== name ? city : undefined, state, "Brasil"].filter(Boolean).join(", "), name, lat: String(c[1]), lon: String(c[0]), type: p.type ?? p.osm_value ?? "city", class: "place", address: { city, country: "Brasil", country_code: "br", ...(state ? { state } : {}) } }; }
async function queryPhoton(q: string): Promise<NominatimResult[]> { const u = new URL("https://photon.komoot.io/api/"); u.searchParams.set("q", q); u.searchParams.set("limit", "20"); u.searchParams.set("lang", "pt"); u.searchParams.set("layer", "city"); try { const r = await fetchWithTimeout(u.toString(), { headers: { Accept: "application/json", "User-Agent": OSM_UA } }, 7000); if (!r.ok) return []; const j = await r.json() as PhotonResponse; return (j.features ?? []).map(photonToNominatimResult).filter((x): x is NominatimResult => x !== null); } catch { return []; } }
async function findPlaceResults(q: string): Promise<NominatimResult[]> { const normalized = normalizeText(q); const direct = await queryPlaces(q); const directRanked = rankPlaceResults(q, direct); const exactOrPrefix = direct.filter((r) => { const name = normalizeText(r.name), city = placeName(r); return name === normalized || city === normalized || name.startsWith(normalized) || city.startsWith(normalized); }); if (exactOrPrefix.length > 0) return rankPlaceResults(q, exactOrPrefix); if (directRanked.length > 0) return directRanked; const photon = await queryPhoton(q); const photonRanked = rankPlaceResults(q, photon); if (photonRanked.length > 0) return photonRanked; return rankFuzzyPlaceResults(normalized, direct);
}
async function queryOverpassMirror(m: string, q: string): Promise<OverpassElement[] | null> { try { const r = await fetchWithTimeout(m, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", "User-Agent": OSM_UA }, body: `data=${encodeURIComponent(q)}` }, 13000); if (!r.ok) return null; const j = await r.json() as { elements?: OverpassElement[] }; return j.elements ?? []; } catch { return null; } }
function merge(responses: Array<OverpassElement[] | null>) { const m = new Map<string, OverpassElement>(); for (const rs of responses) for (const e of rs ?? []) { const k = `${e.type}-${e.id}`; if (!m.has(k)) m.set(k, e); } return [...m.values()]; }
async function queryOverpass(q: string) { const rs = await Promise.all(OVERPASS_MIRRORS.map((m) => queryOverpassMirror(m, q))); if (!rs.some(Boolean)) return null; return merge(rs); }
function splitArea(a: BoundingBox) { const s = Math.min(a.south, a.north), n = Math.max(a.south, a.north), w = Math.min(a.west, a.east), e = Math.max(a.west, a.east), dh = (n - s) / 2, dw = (e - w) / 2; return [0, 1, 2, 3].map((i) => { const row = Math.floor(i / 2), col = i % 2; return { south: s + row * dh, north: row === 1 ? n : s + (row + 1) * dh, west: w + col * dw, east: col === 1 ? e : w + (col + 1) * dw }; }); }
async function queryArea(a: BoundingBox, c: CategoryKey[]) { const rs = await Promise.all(splitArea(a).map((t) => queryOverpass(buildOverpassQuery(t, c, false)))); if (rs.every((x) => x === null)) return null; return merge(rs); }
export const searchPlacesServer = createServerFn({ method: "POST" }).validator((data: { q: string }) => data).handler(async ({ data }): Promise<PlaceSuggestion[]> => { const q = data.q.trim().replace(/\s+/g, " "); if (q.length < 2) return []; const ranked = await findPlaceResults(q); return ranked.map(toPlaceSuggestion); });
export const searchOverpassServer = createServerFn({ method: "POST" }).validator((data: { area: BoundingBox; categories: CategoryKey[] }) => data).handler(async ({ data }) => { const primary = await queryArea(data.area, data.categories); if (primary === null) throw new Error("A fonte de estabelecimentos está indisponível no momento. Tente novamente em alguns segundos."); return { elements: primary }; });
export const verifyLeadsServer = createServerFn({ method: "POST" }).validator((data: { leads: Establishment[] }) => data).handler(async ({ data }): Promise<{ leads: (Establishment & { verification: LeadVerification })[]; external: boolean }> => { if (!externalVerificationConfigured()) return { leads: data.leads.map((lead) => ({ ...lead, verification: { status: "unverified", score: 0, reasons: ["Verificação externa não configurada; usados os dados do OpenStreetMap."], checked: false, foundDigitalPresence: Boolean(lead.signals.website || lead.signals.instagram || lead.contact.whatsappValid || lead.contact.instagramUrl), foundWebsite: Boolean(lead.signals.website || lead.contact.websiteUrl), contactConfidence: "low" as const } })), external: false }; return { leads: await verifyLeads(data.leads), external: true }; });
